run:
	electron .

package:
	electron-packager . "RTA Manager" --platform=darwin --arch=x64 --version=1.7.5 --overwrite

package-win:
	electron-packager . "RTA Manager" --platform=darwin,win32 --arch=x64 --version=1.7.5 --overwrite
